version: "3"
services:
  client:
    image: chaoste/bptc
    command: python main.py -cli -p 8100
    # CLI will try to connect to the TTY
    tty: true
    stdin_open: true
    volumes:
      - client:/home/bptc_wallet/data
    ports:
      - "8100:8100"
      - "8101:8101"
volumes:
  client:
    driver: local
