version: "3"
services:
  # The following two clients are running automatically. This means they don't
  # provide an UI but do everything on their own but the transactions. They can
  # vote and send their hashgraph to other
  # clients.
  client1:
    image: chaoste/bptc
    command: python main.py -auto -p 8000 -r registry:9000 -qm registry:9001
    tty: true
    # stdin_open: true  # Add this if you want to execute the CLI client
    volumes:
      - ../../data/docker/c1:/home/bptc_wallet/data
    ports:
      - "8000:8000"
      - "8001:8001"
    links:
      - registry
  client2:
    image: chaoste/bptc
    command: python main.py -auto -p 8002 -r registry:9000 -qm registry:9001
    tty: true
    volumes:
      - ../../data/docker/c2:/home/bptc_wallet/data
    ports:
      - "8002:8002"
      - "8003:8003"
    links:
      - registry
