version: "3"
services:
  client1:
    image: chaoste/bptc
    command: python main.py --headless -p 8000 -o demo_setup\stakeholders\1\data
    tty: true
    ports:
      - "8000:8000"
      - "8001:8001"
  client2:
    image: chaoste/bptc
    command: python main.py --headless -p 8002 -o demo_setup\stakeholders\2\data
    tty: true
    ports:
      - "8002:8002"
      - "8003:8003"
  client3:
    image: chaoste/bptc
    command: python main.py --headless -p 8004 -o demo_setup\stakeholders\3\data
    tty: true
    ports:
      - "8004:8004"
      - "8005:8005"
  client4:
    image: chaoste/bptc
    command: python main.py --headless -p 8006 -o demo_setup\stakeholders\4\data
    tty: true
    ports:
      - "8006:8006"
      - "8007:8007"
